"""OpenHuntX WebGuard scanner package."""

from .analyzer_registry import (
    AnalyzerOutputError,
    AnalyzerPipelineResult,
    AnalyzerRegistryError,
    PassiveAnalyzer,
    execute_analyzers,
    registered_checks,
    validate_analyzer_registry,
)
from .cookie_analyzer import (
    COOKIE_CHECKS,
    CookieAnalysisError,
    analyze_cookies,
)
from .cors_analyzer import (
    CORS_CHECKS,
    CorsAnalysisError,
    analyze_cors,
)
from .crawler import (
    CrawlCancellationToken,
    CrawlExecution,
    CrawlPageOutcome,
    CrawlPageRecord,
    CrawlPolicy,
    CrawlPolicyError,
    CrawlQueryMode,
    CrawlSkipReason,
    CrawlSkipSummary,
    CrawlTerminationReason,
    DEFAULT_ALLOWED_CONTENT_TYPES,
    DEFAULT_BLOCKED_PATH_SEGMENTS,
    DEFAULT_CRAWL_EXECUTION_SECONDS,
    DEFAULT_CRAWL_REQUEST_ATTEMPTS,
    MAXIMUM_CRAWL_DELAY_SECONDS,
    MAXIMUM_CRAWL_DEPTH,
    MAXIMUM_CRAWL_EXECUTION_SECONDS,
    MAXIMUM_CRAWL_PAGES,
    MAXIMUM_CRAWL_REQUEST_ATTEMPTS,
    MAXIMUM_CRAWL_URL_LENGTH,
    MAXIMUM_LINKS_PER_PAGE,
    PageVisitor,
    crawl_same_origin,
)
from .crawl_scan import run_passive_crawl_scan
from .disclosure_analyzer import (
    DISCLOSURE_CHECKS,
    DisclosureAnalysisError,
    analyze_information_disclosure,
)
from .error_taxonomy import (
    ErrorCategory,
    ErrorPolicy,
    classify_error,
    is_retryable_error,
    known_error_codes,
)
from .header_analyzer import (
    HeaderAnalysisError,
    analyze_security_headers,
)
from .passive_scan import (
    DEFAULT_PASSIVE_ANALYZERS,
    ENGINE_NAME,
    ENGINE_VERSION,
    PASSIVE_CHECKS,
    PASSIVE_COOKIE_CHECKS,
    PASSIVE_CORS_CHECKS,
    PASSIVE_DISCLOSURE_CHECKS,
    PASSIVE_HEADER_CHECKS,
    run_passive_header_scan,
)
from .retry_policy import (
    MAXIMUM_BACKOFF_MULTIPLIER,
    MAXIMUM_BACKOFF_SECONDS,
    MAXIMUM_REQUEST_ATTEMPTS,
    RetryPolicy,
)
from .safe_http import (
    FetchPolicy,
    SafeHttpResponse,
    SafeRequestError,
    fetch_once,
)
from .scope_validator import (
    TargetValidationError,
    ValidatedTarget,
    ValidationMode,
    ValidationPolicy,
    resolve_host,
    validate_target_url,
)

__version__ = "0.1.0"

__all__ = [
    "AnalyzerOutputError",
    "AnalyzerPipelineResult",
    "AnalyzerRegistryError",
    "COOKIE_CHECKS",
    "CORS_CHECKS",
    "CrawlCancellationToken",
    "CrawlExecution",
    "CrawlPageOutcome",
    "CrawlPageRecord",
    "CrawlPolicy",
    "CrawlPolicyError",
    "CrawlQueryMode",
    "CrawlSkipReason",
    "CrawlSkipSummary",
    "CrawlTerminationReason",
    "DEFAULT_ALLOWED_CONTENT_TYPES",
    "DEFAULT_BLOCKED_PATH_SEGMENTS",
    "DEFAULT_CRAWL_EXECUTION_SECONDS",
    "DEFAULT_CRAWL_REQUEST_ATTEMPTS",
    "DEFAULT_PASSIVE_ANALYZERS",
    "DISCLOSURE_CHECKS",
    "ENGINE_NAME",
    "ENGINE_VERSION",
    "ErrorCategory",
    "ErrorPolicy",
    "CookieAnalysisError",
    "CorsAnalysisError",
    "DisclosureAnalysisError",
    "FetchPolicy",
    "HeaderAnalysisError",
    "MAXIMUM_BACKOFF_MULTIPLIER",
    "MAXIMUM_BACKOFF_SECONDS",
    "MAXIMUM_CRAWL_DELAY_SECONDS",
    "MAXIMUM_CRAWL_DEPTH",
    "MAXIMUM_CRAWL_EXECUTION_SECONDS",
    "MAXIMUM_CRAWL_PAGES",
    "MAXIMUM_CRAWL_REQUEST_ATTEMPTS",
    "MAXIMUM_CRAWL_URL_LENGTH",
    "MAXIMUM_LINKS_PER_PAGE",
    "MAXIMUM_REQUEST_ATTEMPTS",
    "PASSIVE_CHECKS",
    "PASSIVE_COOKIE_CHECKS",
    "PASSIVE_CORS_CHECKS",
    "PASSIVE_DISCLOSURE_CHECKS",
    "PASSIVE_HEADER_CHECKS",
    "PageVisitor",
    "PassiveAnalyzer",
    "RetryPolicy",
    "SafeHttpResponse",
    "SafeRequestError",
    "TargetValidationError",
    "ValidatedTarget",
    "ValidationMode",
    "ValidationPolicy",
    "__version__",
    "analyze_cookies",
    "analyze_cors",
    "analyze_information_disclosure",
    "analyze_security_headers",
    "classify_error",
    "crawl_same_origin",
    "execute_analyzers",
    "fetch_once",
    "is_retryable_error",
    "known_error_codes",
    "registered_checks",
    "resolve_host",
    "run_passive_crawl_scan",
    "run_passive_header_scan",
    "validate_analyzer_registry",
    "validate_target_url",
]
