"""Slice 17 requirement 1/6: ProductionMailProvider's Postmark-shaped
delivery logic, against a fake PostmarkClientProtocol -- no real
network call, matching this project's established duck-typed-client
test pattern (see test_signing_provider.py for the same approach
against KmsClientProtocol).
"""

from __future__ import annotations

import unittest

from webguard_api.mail import MailDeliveryError, PostmarkHttpClient, ProductionMailProvider


class _FakePostmarkClient:
    def __init__(self, responses: list) -> None:
        self._responses = list(responses)
        self.payloads: list[dict] = []

    def send_email(self, payload: dict) -> dict:
        self.payloads.append(payload)
        response = self._responses.pop(0)
        if isinstance(response, Exception):
            raise response
        return response


def _success(message_id: str = "msg-1") -> dict:
    return {"status_code": 200, "body": {"ErrorCode": 0, "Message": "OK", "MessageID": message_id}}


def _error(status_code: int, error_code: int, message: str = "vendor detail") -> dict:
    return {"status_code": status_code, "body": {"ErrorCode": error_code, "Message": message}}


class ProductionMailProviderTests(unittest.TestCase):
    def setUp(self) -> None:
        self.sleeps: list[float] = []

    def provider(self, responses: list) -> tuple[ProductionMailProvider, _FakePostmarkClient]:
        client = _FakePostmarkClient(responses)
        return (
            ProductionMailProvider(client, from_address="alerts@webguard.example", sleep=self.sleeps.append),
            client,
        )

    def test_successful_send_makes_exactly_one_request(self) -> None:
        provider, client = self.provider([_success()])
        provider.send(to="user@example.com", subject="Hi", body="body", category="email_verification")
        self.assertEqual(len(client.payloads), 1)
        self.assertEqual(client.payloads[0]["To"], "user@example.com")
        self.assertEqual(client.payloads[0]["From"], "alerts@webguard.example")
        self.assertEqual(client.payloads[0]["Tag"], "email_verification")
        self.assertEqual(self.sleeps, [])

    def test_temporary_failure_is_retried_once_with_the_identical_payload(self) -> None:
        provider, client = self.provider([_error(500, 0), _success()])
        provider.send(to="user@example.com", subject="Hi", body="body with a token", category="password_reset")
        self.assertEqual(len(client.payloads), 2)
        # The retried payload is byte-identical -- a one-time token
        # embedded in it is never regenerated by a transport retry.
        self.assertEqual(client.payloads[0], client.payloads[1])
        self.assertEqual(self.sleeps, [0.5])

    def test_temporary_failure_exhausting_retries_raises_with_temporary_category(self) -> None:
        provider, client = self.provider([_error(503, 0), _error(503, 0)])
        with self.assertRaises(MailDeliveryError) as caught:
            provider.send(to="user@example.com", subject="Hi", body="body", category="invitation")
        self.assertEqual(caught.exception.category, "temporary")
        self.assertEqual(len(client.payloads), 2)

    def test_permanent_failure_is_never_retried(self) -> None:
        provider, client = self.provider([_error(406, 406, "inactive recipient")])
        with self.assertRaises(MailDeliveryError) as caught:
            provider.send(to="bounced@example.com", subject="Hi", body="body", category="invitation")
        self.assertEqual(caught.exception.category, "permanent")
        self.assertEqual(len(client.payloads), 1)
        self.assertEqual(self.sleeps, [])

    def test_configuration_failure_is_never_retried(self) -> None:
        provider, client = self.provider([_error(401, 10, "invalid API token")])
        with self.assertRaises(MailDeliveryError) as caught:
            provider.send(to="user@example.com", subject="Hi", body="body", category="email_verification")
        self.assertEqual(caught.exception.category, "configuration")
        self.assertEqual(len(client.payloads), 1)

    def test_rate_limited_failure_is_never_retried(self) -> None:
        provider, client = self.provider([_error(429, 0, "too many requests")])
        with self.assertRaises(MailDeliveryError) as caught:
            provider.send(to="user@example.com", subject="Hi", body="body", category="email_verification")
        self.assertEqual(caught.exception.category, "rate_limited")
        self.assertEqual(len(client.payloads), 1)

    def test_transport_timeout_is_retried_once(self) -> None:
        timeout_error = MailDeliveryError("mail_transport_timeout", "timed out", category="timeout")
        provider, client = self.provider([timeout_error, _success()])
        provider.send(to="user@example.com", subject="Hi", body="body", category="email_verification")
        self.assertEqual(len(client.payloads), 2)

    def test_vendor_message_text_never_appears_on_the_raised_error(self) -> None:
        """Requirement 20: no vendor leakage -- the raised error's own
        `.message` must never contain the vendor's raw response text,
        even though that text was present in the response body. Uses a
        permanent (406) classification specifically so it is not
        retried, keeping this test about leakage, not retry count."""
        secret_vendor_detail = "AWS RequestId 12345 SES rejected recipient domain xyz"
        provider, _ = self.provider([_error(406, 406, secret_vendor_detail)])
        with self.assertRaises(MailDeliveryError) as caught:
            provider.send(to="user@example.com", subject="Hi", body="body", category="email_verification")
        self.assertNotIn(secret_vendor_detail, caught.exception.message)
        self.assertNotIn(secret_vendor_detail, str(caught.exception))

    def test_success_requires_both_status_200_and_error_code_zero(self) -> None:
        """A 200 with a non-zero Postmark ErrorCode is still a failure
        -- status code alone is not sufficient evidence of delivery.
        This shape is ambiguous enough to fall into this module's
        generic "temporary" fallback, so it is retried once before
        the caller sees a failure."""
        response = {"status_code": 200, "body": {"ErrorCode": 300, "Message": "bad"}}
        provider, client = self.provider([response, response])
        with self.assertRaises(MailDeliveryError):
            provider.send(to="user@example.com", subject="Hi", body="body", category="email_verification")
        self.assertEqual(len(client.payloads), 2)


class PostmarkHttpClientTests(unittest.TestCase):
    def test_send_email_raises_timeout_category_on_socket_timeout(self) -> None:
        client = PostmarkHttpClient(server_token="fake-token", timeout_seconds=0.001)

        class _AlwaysTimesOut:
            def __init__(self, *_args, **_kwargs) -> None:
                pass

            def request(self, *_args, **_kwargs) -> None:
                raise TimeoutError("simulated timeout")

            def close(self) -> None:
                pass

        import webguard_api.mail as mail_module

        original = mail_module.http.client.HTTPSConnection
        mail_module.http.client.HTTPSConnection = _AlwaysTimesOut  # type: ignore[assignment]
        try:
            with self.assertRaises(MailDeliveryError) as caught:
                client.send_email({"To": "user@example.com"})
            self.assertEqual(caught.exception.category, "timeout")
        finally:
            mail_module.http.client.HTTPSConnection = original


if __name__ == "__main__":
    unittest.main()
